### ISSUE TITLE
New feature: Sound Effects

### ISSUE THREAD

**Issue by microbit-carlos** [microbit-foundation/micropython-microbit-v2#103]
Proposal in the docs:
- https://github.com/bbcmicrobit/micropython/pull/753

**Comment by microbit-carlos** [comment]
@dpgeorge let me know if there is anything I can do to facilitate this.

**Comment by dpgeorge** [comment]
See #106 for an initial implementation.  It's on the `audio-sound-effect` branch in this repo.

**Comment by dpgeorge** [comment]
Implemented in 9a5958bbe41dc05ef93a338ff08d4fcc2ef5d886 and 822b3c9e88f6f3faa4af458db7e35e1a818882de

**Comment by microbit-carlos** [comment]
Thanks Damien! I've created https://github.com/microbit-foundation/micropython-microbit-v2/issues/110 to capture the Foundation task to create the predefined SoundEffects.
