### ISSUE TITLE
Module in the filesystem has the __class__ dunder

### ISSUE THREAD

**Issue by microbit-carlos** [microbit-foundation/micropython-microbit-v2#104]
With a `my_module.py` file that only contains `FOO = 0`:
```
MicroPython 569e361 on 2022-06-20; micro:bit v2.0.0 with nRF52833
Type "help()" for more information.
>>> import my_module
>>> dir(my_module)
['__class__', '__name__', 'FOO']
>>> my_module.__class__
<class 'module'>
```

I don't think the `__class__` attribute here is correct? Trying the same in CPython doesn't have that dunder attribute.

**Comment by dpgeorge** [comment]
> Trying the same in CPython doesn't have that dunder attribute.

CPython does have it, it's just not listed by `dir(...)`.  Try `my_module.__class__` under CPython and you get the same as MicroPython.

**Comment by jaustin** [comment]
We're curious to know why CPython doesn't show this, but happy to close this as an issue :)

**Comment by dpgeorge** [comment]
> We're curious to know why CPython doesn't show this

Honestly, I don't know!  Maybe it filters out `__class__` from dir on modules.
