### ISSUE TITLE
Button B pin11 digital read always returns 0 

### ISSUE THREAD

**Issue by microbit-carlos** [microbit-foundation/micropython-microbit-v2#136]
Button B is pin 11, when `pin11.read_digital()` is executed, it always returns 0.

For a simple replicator, you can see how pressing button A changes pin5 value, but pin11 is always low:

```python
from microbit import *

while True:
    print(pin5.read_digital(), pin11.read_digital())
    sleep(150)
```

This works fine on a V1.

**Comment by dpgeorge** [comment]
pin11 was accidentally defined to be pin 12.  Fixed by 1955adb1d9bf0afb8020d375fb63c4c21afc2335
