### ISSUE TITLE
microbit v2.21 with v2.1.0.hex

### ISSUE THREAD

**Issue by DCCTT** [microbit-foundation/micropython-microbit-v2#140]
Can i use microbit v2.21 with [micropython-microbit-v2.1.0.hex]?
and
Is there a hex file corresponding to microbit v2.21？
(•◡•)

**Comment by microbit-carlos** [comment]
Hi @DCCTT,

You can use any release from this repository (v2.x.x) with any micro:bit V2 (V2.00 or V2.2x).

Hope that resolves your question, feel free to reopen the issue if you have any other queries 👍
