### ISSUE TITLE
How do we embed custom frozen modules into the v2 firmware?

### ISSUE THREAD

**Issue by z-zawhtet-a** [microbit-foundation/micropython-microbit-v2#157]
Hi,

For microbit v1, I can do so by following the steps described here [https://github.com/bbcmicrobit/micropython/issues/555#issuecomment-419491671](url). Are there similar steps that I can follow for the v2 firmware?

Thank you!

**Comment by dpgeorge** [comment]
You can add your frozen code to `src/codal_port/manifest.py` and rebuild.

**Comment by z-zawhtet-a** [comment]
Thanks much! It works!
