### ISSUE TITLE
Implement `microphone.set_sensitivity(gain)`

### ISSUE THREAD

**Issue by microbit-carlos** [microbit-foundation/micropython-microbit-v2#184]
As discussed in:
- https://github.com/microbit-foundation/micropython-microbit-v2/pull/163#issuecomment-2017821708

The following values can be provided in the `microphone` module:
- `SENSITIVITY_LOW` = 0.079
- `SENSITIVITY_MEDIUM` = 0.2 (the default)
- `SENSITIVITY_HIGH` = 1.0

e.g. `microphone.set_sensitivity(microphone.SENSITIVITY_HIGH)`

**Comment by dpgeorge** [comment]
Now implemented in the branch/PR.
