### ISSUE TITLE
Update microphone "sound" methods to use the word "event" instead

### ISSUE THREAD

**Issue by microbit-carlos** [microbit-foundation/micropython-microbit-v2#19]
To avoid confusion with the new class "Sound" for the audio module.

- `microphone.current_sound` -> `microphone.current_event`
- `microphone.is_sound` -> `microphone.is_event`
- `microphone.was_sound` -> `microphone.was_event`
- `microphone.get_sound` -> `microphone.get_event`

**Comment by jaustin** [comment]
Similar to #20 we're assuming this for resources.

**Comment by dpgeorge** [comment]
Done in 0d1c10b37bc7de0f7efae9a9695f7a1587f856c2
