### ISSUE TITLE
microphone sensitivity values are not correct

### ISSUE THREAD

**Issue by microbit-carlos** [microbit-foundation/micropython-microbit-v2#204]
```
>>> microphone.SENSITIVITY_HIGH
1
>>> microphone.SENSITIVITY_MEDIUM
0
>>> microphone.SENSITIVITY_LOW
0
>>>
```

So, when trying to record with medium or low sensitivity the AudioFrame is blank.

**Comment by microbit-carlos** [comment]
https://github.com/microbit-foundation/micropython-microbit-v2/pull/163/files#r1578412276

**Comment by dpgeorge** [comment]
Oops, that was an oversight.  Now fixed.

**Comment by microbit-carlos** [comment]
Thanks Damien!
