### ISSUE TITLE
Feature request: Expose CODAL method to calibrate touch pins

### ISSUE THREAD

**Issue by microbit-carlos** [microbit-foundation/micropython-microbit-v2#209]
This has been requested a few times, and I've myself missed having this functionality during a workshop.

Essentially CODAL currently contains pre-calibrated values for the touch pins and touch logo, which it's simple and saves having to run the calibration during startup (which we've found in the past can be confusing if users are holding the micro:bit while it's being flashed).
The disadvantage is that cap touch input stops working when we attach things like crocodile clips or copper tape to the pins, so being able to trigger a recalibration would help resolve this.

Suggested function name would be `pin.calibrate()` and can use the `NRF52Pin.touchCalibrate()` CODAL API.
https://github.com/lancaster-university/codal-nrf52/blob/62da916a409c7bc921f17d881e8da1cb35a856a6/inc/NRF52Pin.h#L334

**Comment by dpgeorge** [comment]
See #222 for an implementation.

**Comment by dpgeorge** [comment]
Implemented in 3f22f306bcbc3461b0c3c60702b74bbce6689013

**Comment by microbit-carlos** [comment]
Added docs to an existing touch pin PR:
- https://github.com/bbcmicrobit/micropython/pull/802
