### ISSUE TITLE
`audio.play()` with AudioFrames returns before they are played

### ISSUE THREAD

**Issue by microbit-carlos** [microbit-foundation/micropython-microbit-v2#212]
With the latest recording and playback from CI (merge commit build):
https://github.com/microbit-foundation/micropython-microbit-v2/actions/runs/10210863635?pr=163

```python
>>> af = audio.AudioFrame()
>>> ms_start = microbit.running_time(); audio.play(af); ms_end = microbit.running_time()
>>> ms_end - ms_start
0
```

Playing a list of them, to ensure it's not the same issue as https://github.com/microbit-foundation/micropython-microbit-v2/issues/182:

```python
>>> audioframes_102_ms = [audio.AudioFrame()] * 25
>>> ms_start = microbit.running_time(); audio.play(audioframes_102_ms); ms_end = microbit.running_time()
>>> ms_end - ms_start
1
```

It's the same with the `wait=True` flag:
```python
>>> ms_start = microbit.running_time(); audio.play(audioframes_102_ms, wait=True); ms_end = microbit.running_time()
>>> ms_end - ms_start
1
```

**Comment by dpgeorge** [comment]
This was a left-over from when AudioFrame had a `used_size` attribute.  In the tests above the AudioFrame takes 0 time to play be cause `used_size` is 0.

I've now removed the `used_size` attribute from AudioFrame (latest commit in the `audio-recording` branch).

**Comment by microbit-carlos** [comment]
Thanks Damien! I can confirm this as been fixed in the latest CI build.
