### ISSUE TITLE
Examples: is it appropriate to have a samples repo that would be okay to merge upstream?

### ISSUE THREAD

**Issue by jaustin** [microbit-foundation/micropython-microbit-v2#22]
In bbcmicrobit/micropython we have a samples folder, and there are already request for shipping some V2 samples. This seems sensible.

As the eventual goal for this repository is to move upstream, we wanted to check whether @dpgeorge would accept a samples/examples directory there or whether we need to start that elsewhere.

**Comment by dpgeorge** [comment]
Yes we have an `examples/` directory upstream with various example scripts.  So would make sense to put microbit examples there as well, eg `examples/microbit/`
