### ISSUE TITLE
Music and LCD problem

### ISSUE THREAD

**Issue by crouse12** [microbit-foundation/micropython-microbit-v2#25]
Please watch the following code.
![image](https://user-images.githubusercontent.com/25700616/99147453-01c00280-26bc-11eb-8335-ab6d943e5e05.png)
I found that music will play after LED screen show 'Hello, World!'.
I want they play at the same time.
Is it possible?

**Comment by microbit-carlos** [comment]
Hi @crouse12,
You can use the `wait` argument in scroll to do that: `display.scroll('Hello, World!', wait=False)`
https://microbit-micropython.readthedocs.io/en/latest/display.html

**Comment by crouse12** [comment]
Thanks for your help. I will test it.
Can music.play execute in the background, too?
I try to use micropython to create scratch 3.0 blocks for microbit v2 now.
music.play and display.scroll usually make some mistakes for my scrath 3.0 blocks, when i read movement and gestures at the same time.
https://www.youtube.com/watch?v=hKWrgvlkIow&t=6s

**Comment by microbit-carlos** [comment]
https://microbit-micropython.readthedocs.io/en/latest/music.html#music.play

Although there is some undergoing work right now with all the sound-generating stuff and some things might not work yet.

**Comment by crouse12** [comment]
Thanks.
I will wait them.

**Comment by microbit-carlos** [comment]
This should be working in the latest https://python.microbit.org/v/beta (beta.7).
If you find any issues could you let us know by opening new bug reports? Thanks!

**Comment by crouse12** [comment]
> This should be working in the latest https://python.microbit.org/v/beta (beta.7).
> If you find any issues could you let us know by opening new bug reports? Thanks!

The latest python editor solves this problem. Thanks.
