### ISSUE TITLE
current_sound() cannot work

### ISSUE THREAD

**Issue by crouse12** [microbit-foundation/micropython-microbit-v2#34]
Python editor:
Editor Version: 2.2.0-beta.1
MicroPython Version: 1.0.1/2.0.0-beta.1

![image](https://user-images.githubusercontent.com/25700616/100748515-600c1580-341e-11eb-8f70-793474827b66.png)
Why does this function current_sound disappear?

**Comment by microbit-carlos** [comment]
We added the `SoundEvent` class and now it's microphone.current_event().
More info can be found in this ticket: https://github.com/microbit-foundation/micropython-microbit-v2/issues/19

And the upcoming docs update: https://github.com/bbcmicrobit/micropython/pull/692
