### ISSUE TITLE
uart problem

### ISSUE THREAD

**Issue by crouse12** [microbit-foundation/micropython-microbit-v2#35]
I found that uart in microbit v2 has a problem if I follow the following steps.
(1)
Connect to microbit v2 by using putty,
(2)
Reset the microbit v2's power.
(3)
Connect to microbit v2 by using putty, 
You can find that microbit v2 cannot work correctly.

https://youtu.be/ZrAsxoCKZTo

**Comment by dpgeorge** [comment]
Yes I have seen that issue before, that sometimes on initial connection the REPL is not responsive and just returns garbage characters.

@microbit-carlos I'm not sure where the issue lies, maybe with DAP link?

The fix is to press the reset button on the back of the microbit.

**Comment by crouse12** [comment]
Can you clear buffers or session when the Microbit v2 start?

**Comment by crouse12** [comment]
Can anyone help me to solve uart problem?

**Comment by martinwork** [comment]
Problem exists with a C++ test too.

**Comment by dpgeorge** [comment]
> Problem exists with a C++ test too.

Can you please post C++ code that reproduces it?  I guess it's an issue with the CODAL and initialisation of the serial UART?

**Comment by martinwork** [comment]
@dpgeorge https://github.com/lancaster-university/codal-microbit-v2/issues/45

**Comment by dpgeorge** [comment]
See also https://github.com/lancaster-university/codal-microbit-v2/issues/55

**Comment by dpgeorge** [comment]
Fixed by df3caf7176188303686801a1f1fe6e6496d346ad
