### ISSUE TITLE
Backspace correction echo fails in Mu Repl

### ISSUE THREAD

**Issue by AllegroGavin** [microbit-foundation/micropython-microbit-v2#39]
I'm using beta.2 with Mu 1.1.0.alpha.2 on Windows 10 (have not tried beta.1) and frequently when trying to use backspace to correct input in the repl it will echo specific garbage. For example, here I have typed 12345678 and then hit backspace several times, the first few times it works correctly, then it spits out the (crossed box)[K sequence. The repl received and acted on the backspace.

![image](https://user-images.githubusercontent.com/1420200/101421531-1d34bc80-38ba-11eb-9ef3-a505aa16752d.png)

It's always this same three character sequence, and it tends to occur in bursts, i.e. I can hold down backspace and maybe for 15 characters it's fine but then I get a burst of the three characters a few times in a row. It only appears to be the backspace that shows a visible issue.

I presume it's trying to output (backspace)(space)(backspace) but is glitching somehow in the serial data stream etc.

**Comment by martinwork** [comment]
I can hit problems with backspace in the Mu REPL quite easily, but not in the python.microbit.org REPL or tera term.

**Comment by dpgeorge** [comment]
This seems like a problem with Mu's handling of escape sequences.

**Comment by jaustin** [comment]
@microbit-carlos is going to see if this is also visible on V1 with Mu - anyone who has seen it there please shout!

**Comment by microbit-carlos** [comment]
I gave this a go with the Mu alpha.2 release (same as @AllegroGavin, which doesn't include some of the latest changes in how it processes space sequences) and I can easily reproduce this in V2 but not in V1.


In this crude test I just type `asd` as fast as i can while pressing the backspace key as well.
In V2 we can see at least 7 cases where the scape sequence is missing something and printed back:

![v2-backspace](https://user-images.githubusercontent.com/29712657/102127097-f808f680-3e43-11eb-8634-23afa573ced7.gif)

V1 with twice the "samples" i couldn't get a single hit:

![v1-backspace](https://user-images.githubusercontent.com/29712657/102127174-13740180-3e44-11eb-9a77-9f560414d5e1.gif)

**Comment by microbit-carlos** [comment]
Actually an easier way to replicate is to fill the REPL line with text and then keep the backspace key pressed.

The incomplete scape sequence gets sometimes printed and immediately deleted, but it looks like it gets correctly processed inside the MicroPython buffer, since at some point it stops removing characters and the history (up arrow) shows an empty buffer:

![v2-back](https://user-images.githubusercontent.com/29712657/102128729-36071a00-3e46-11eb-89c1-760dd0947ddc.gif)

Could not replicate this with V1.

**Comment by dpgeorge** [comment]
This could be related to #15

**Comment by microbit-carlos** [comment]
In the end this was a problem on Mu that was somehow easier to trigger with V2.

The escape characters processing has been updated in the Mu repository, but there isn't an official release yet.
From the work that was carried out at the time, I think this is to do with the fact that Mu used to break up the serial processing in blocks of 20 bytes and that could divide the bytes of a scape sequence.

@AllegroGavin if you like you test a Windows CI build (down in the artifacts section) and that should should not present the issue anymore: https://github.com/mu-editor/mu/actions/runs/419131068

**Comment by AllegroGavin** [comment]
Yes, I can confirm the problem is no longer detectable using the new Mu build artifact version.

Thanks for looking into it!
