### ISSUE TITLE
Neopixel Module Not Available

### ISSUE THREAD

**Issue by JoshuaLowe1002** [microbit-foundation/micropython-microbit-v2#4]
Apologies if you're already aware of this bug but it seems the neopixel module does not exist in MicroPython on V2.

Maybe an issue linked to https://github.com/microsoft/pxt-microbit/issues/3415

![image](https://user-images.githubusercontent.com/25752941/96098801-71c74700-0eca-11eb-9cc0-ba9f8d31a177.png)

**Comment by microbit-mark** [comment]
This module is also requested via micro:bit support in https://support.microbit.org/a/tickets/40468

**Comment by martinwork** [comment]
@microbit-mark @microbit-carlos Needed for testing "display_and_neopixel.py"

**Comment by microbit-carlos** [comment]
Yes, this is something we wanted to implement in the CODAL layer, so I've opened https://github.com/lancaster-university/codal-microbit-v2/issues/19.

**Comment by jaustin** [comment]
The older implementation doesn't co-exist with Bluetooth so I think it does make sense to use the PWM-based one. @finneyj any thoughts on merging that so we can ensure Neopixel in MicroPython?  Would it require a dedicated PWM channel?

**Comment by finneyj** [comment]
Yes, I agree we should build a PWM-based driver codal side. It does require a dedicated PWM peripheral, but I have one reserved for this already, so no problem.

Sam's driver needs a bit of work as I recall to package so that it is memory safe during DMA and double buffers to avoid memory overhead/glitching. I'll happily do that when I get a minute.

**Comment by dpgeorge** [comment]
Ideally CODAL would expose a single function like `neopixel_write(pin, len, buf)` that would output the given `buf` of data on the `pin` using neopixel encoding.

**Comment by microbit-carlos** [comment]
NeoPixel support has been added to CODAL: https://github.com/lancaster-university/codal-nrf52/blob/master/inc/neopixel.h
Thanks @finneyj !

**Comment by finneyj** [comment]
no worries @dpgeorge @microbit-carlos.

Please note this is a blocking call (it will block the calling fiber until playout is complete), but doesn't disable interrupts or anything like that, so shouldn't have any of the side effects associated with the old bit banging implementations. 

Under the hood it all runs async, so see here if you prefer it to just run in the background. You just need to flip play() to playAsync(): 

https://github.com/lancaster-university/codal-nrf52/blob/master/source/neopixel.cpp#L25

https://github.com/lancaster-university/codal-nrf52/blob/master/source/WS2812B.cpp#L129

**Comment by dpgeorge** [comment]
Thanks @finneyj !  A blocking call is good enough for now.

Implemented on the Python side in 915b6aa746ce35d40862b973c4dd519ff11109f2, should be compatible with micro:bit v1, and also includes support for RGBW LEDs.

**Comment by microbit-carlos** [comment]
@microbit-mark @martinwork this should be ready for testing on the next MicroPython release.

**Comment by microbit-carlos** [comment]
@dpgeorge the `ws2812_write` function is also exposed via `microbit` module (`microbit.ws2812_write`), is that expected?

**Comment by dpgeorge** [comment]
> the `ws2812_write` function is also exposed via `microbit` module (`microbit.ws2812_write`), is that expected?

Yes that's expected, although at this stage I wouldn't document the function as it may change and/or be removed in the future.

We could move it out of the `microbit` module into something like `_microbit` intended for hidden functions if that is a better approach.
