### ISSUE TITLE
Error message does not scroll line number on V2

### ISSUE THREAD

**Issue by microbit-mark** [microbit-foundation/micropython-microbit-v2#56]
> micro:bit support #42322

> Micro bit v2 will tell you if there is an error eg syntax or name error, but, unlike the original microbit,  does not specify which line the error is on.  It shows a sad face then the error message.  Is there any way, other than using the original microbit, to locate the error?

This is true both of the scrolling message and in the REPL.

V1 contains the line number
V2 does not contain the line number

Could we still offer the line number for V2 to help people locate the error?

**Comment by carlosperate** [comment]
Have you tried this in the beta editor? I think it's been included in the beta.3 release of MicroPython.

**Comment by microbit-mark** [comment]
Thanks @microbit-carlos. Tested in https://python.microbit.org/v/beta and this is resolved

**Comment by microbit-carlos** [comment]
Great, thanks for checking. I'll close this issue then.
