### ISSUE TITLE
Error displays incorrect line

### ISSUE THREAD

**Issue by microbit-mark** [microbit-foundation/micropython-microbit-v2#59]
> micro:bit support: #42322

In this example, a syntax error is introduces on line 3, removing the `:` from the loop

```Python
from microbit import *

while True
    display.scroll(str(temperature()))
    display.scroll(' celsius ')
```

However, The micro:bit displays that there is a syntax error on line 4. This is the same in the REPL console.

It should display line 3.

The ticket requester states that this does not reproduce in Mu though, which I expect means that it does not reproduce for V1 boards

**Comment by microbit-carlos** [comment]
Just to add a bit more info, I tried this in a V1 and the error report is the same at line 4.
The comment about Mu might be from the editor error checker:
![image](https://user-images.githubusercontent.com/29712657/105048922-06aa8500-5a64-11eb-8142-570511b41660.png)

Not sure to what extent I'd consider this a bug to fix, it'd be an upstream change.

**Comment by jaustin** [comment]
@dpgeorge do you have any plans to change this upstream? Otherwise I think we should close for now as 'v1/v2 behave the same'

**Comment by dpgeorge** [comment]
This is a generic "feature" of MicroPython that is in all ports.  There are no plans to change it, I don't think it's that confusing.

**Comment by microbit-carlos** [comment]
Thanks Damien, we'll close this as something that won't be changed.
