### ISSUE TITLE
Add `antigravity`, `love`, and `this` modules from v1

### ISSUE THREAD

**Issue by microbit-carlos** [microbit-foundation/micropython-microbit-v2#61]
- https://github.com/bbcmicrobit/micropython/pull/181
- https://github.com/bbcmicrobit/micropython/pull/32/
- https://github.com/bbcmicrobit/micropython/pull/4

**Comment by dpgeorge** [comment]
Done in ea28ef4cb54d86ff23579344997a815f0062241f, 3c9983e6385f8036cc71af5b07a3cefa6fb5c427 and 8e5eda1a15e82f67befc9d6ea74188598a05fa09
