### ISSUE TITLE
Feature request: accelerometer.get_strength()

### ISSUE THREAD

**Issue by microbit-mark** [microbit-foundation/micropython-microbit-v2#81]
The MakeCode editor has a block for the 'strength' of the accelerometer defined in https://github.com/microsoft/pxt-microbit/blob/d80514bda223f729d452c1e51047f3272a2317fb/sim/state/accelerometer.ts#L173

<img width="417" alt="image" src="https://user-images.githubusercontent.com/31242877/122236143-2e3c3700-ceb6-11eb-9368-c7f3edc65ae5.png">

It would be useful for students and those making equivalent MicroPython projects to have this API

**Comment by whaleygeek** [comment]
Thanks @microbit-mark this is a small but real omission from MicroPython.

As a content writer I am finding more and more organisations are asking me to provide resources in *both* MakeCode and MicroPython, so correspondence of facilities between the two is becoming a common trend. Anything simple that either editor can do to be more aligned with the other will always be a good thing.

**Comment by dpgeorge** [comment]
If added, needs to also be added in v1.

**Comment by dpgeorge** [comment]
The `get_strength()` method was added in b90a60cae8fc869077b9577011455a442e70aba5

It was also added in v1.
