### ISSUE TITLE
Bluetooth on v2: error

### ISSUE THREAD

**Issue by msalat** [microbit-foundation/micropython-microbit-v2#84]
Found `src/codal_app/codal.json`. Tried `"MICROBIT_BLE_ENABLED" : 1,` instead of `0`. 

Did not work, so tried `DEVICE_STACK_SIZE` 16384 + 32768 instead of 8192 — nothing helped, microbit_v2 shows `0` `7` `1` :cry: 

Even after bluetooth pairing…

**Comment by microbit-carlos** [comment]
Thanks for the report @msalat, I'll close this one as the conversation continued in https://github.com/microbit-foundation/micropython-microbit-v2/issues/51.
