### ISSUE TITLE
Python 3 is sometimes installed as python on systems.

### ISSUE THREAD

**Issue by DaveAtKitronik** [microbit-foundation/micropython-microbit-v2#85]
Trying to build following the instructions I got  a slightly cryptic error:
$ make V=1 -C lib/micropython/mpy-cross
make: Entering directory '/home/Dave/micropython-microbit-v2/lib/micropython/mpy-cross'
python3 ../py/makeversionhdr.py build/genhdr/mpversion.h
make: python3: No such file or directory
make: *** [../py/py.mk:246: build/genhdr/mpversion.h] Error 127
make: Leaving directory '/home/Dave/micropython-microbit-v2/lib/micropython/mpy-cross'

I initially thought it had come from python, but its from make complaining it cant find python (I really should read more carefully)
I am building on a clean Cygwin installation - where python 3 is installed as python 
this is fixed by making a symlink:
 ln /usr/bin/python /usr/bin/python3

I had this same issue previously when working on the V1 micropython, but had forgotten it. 
A small addition to the readme to mention it would have saved me a few hours, and potentially others as well.

**Comment by dpgeorge** [comment]
> A small addition to the readme to mention it would have saved me a few hours, and potentially others as well.

Done in 429d5c6a1da7bf04ff7a02746477b47d81a3983d
