### ISSUE TITLE
Undefined symbols for arm64 - Issue building micropython v2

### ISSUE THREAD

**Issue by scath999** [microbit-foundation/micropython-microbit-v2#89]
Have tried to build this project per the instructions for building v2 [here](https://microbit-micropython.readthedocs.io/en/v2-docs/devguide/flashfirmware.html#id2).

End up with the following link error:

```
LINK mpy-cross
Undefined symbols for architecture arm64:
  "_nlr_push", referenced from:
      _mp_iternext in runtime.o
      _it_iternext in objgetitemiter.o
      _main_ in main.o
     (maybe you meant: _nlr_push_tail)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [mpy-cross] Error 1
```

Any help?

**Comment by microbit-carlos** [comment]
What OS and architecture are you using? Is it Linux or macOS in arm64?

**Comment by scath999** [comment]
My bad.
Mac M1 - Monterey

**Comment by microbit-carlos** [comment]
Thanks @scath999, looks like it might be this issue: https://github.com/micropython/micropython/issues/7232

You could apply the patches listed there locally, or maybe try if you can install x86 gcc with rosetta and that might work?

**Comment by scath999** [comment]
@microbit-carlos Much appreciated. That did fix the one issue - have now found others, but that's my boat to row.

Cheers!
